### ISSUE TITLE
tar does not exist in Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by felipeerazoeld** [Joshua-Riek/ubuntu-apalis-imx8#1]
Hi! after following all the steps this message is showed:

make -C /media/mypc/Users/fe/ubuntu-apalis-imx8/build/linux-toradex M=/media/mypc/Users/fe/ubuntu-apalis-imx8/build/device-tree-overlays/overlays
make[1]: Entering directory '/media/mypc/Users/fe/ubuntu-apalis-imx8/build/linux-toradex'
  Building modules, stage 2.
  MODPOST 0 modules
make[1]: Leaving directory '/media/mypc/Users/fe/ubuntu-apalis-imx8/build/linux-toradex'
Error: '/media/mypc/Users/fe/ubuntu-apalis-imx8/build/*.tar' does not exist
Error: in ./build.sh on line 21

And in fact the tar file not exit:

ll /media/mypc/Users/fe/ubuntu-apalis-imx8/build/
total 28936
drwxr-xr-x 10 root     root         4096 ago 23 08:51 ./
drwxr-xr-x  4 root     root         4096 ago 23 08:29 device-tree-overlays/
drwxr-xr-x 19 root     root         4096 ago 23 08:16 imx-atf/
drwxr-xr-x 11 root     root         4096 ago 23 08:17 imx-mkimage/
drwxr-xr-x  4     1002     1015     4096 fev  9  2022 imx-seco/
-rw-r--r--  1 root     root         6095 ago 23 08:51 linux-5.4.193-toradex_5.4.193-toradex-1_arm64.buildinfo
-rw-r--r--  1 root     root         2180 ago 23 08:51 linux-5.4.193-toradex_5.4.193-toradex-1_arm64.changes
-rw-r--r--  1 root     root     11357240 ago 23 08:51 linux-headers-5.4.193-toradex_5.4.193-toradex-1_arm64.deb
-rw-r--r--  1 root     root     17105452 ago 23 08:51 linux-image-5.4.193-toradex_5.4.193-toradex-1_arm64.deb
-rw-r--r--  1 root     root      1105980 ago 23 08:51 linux-libc-dev_5.4.193-toradex-1_arm64.deb
drwxr-xr-x 27 root     root         4096 ago 23 08:51 linux-toradex/
drwxr-xr-x  2 root     root         4096 ago 23 08:40 rootfs/
drwxr-xr-x  2 root     root         4096 ago 23 08:16 scfw-bin/
drwxr-xr-x 25 root     root         4096 ago 23 08:43 u-boot-toradex/

uname -a
Linux CPQGESPE035W79 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Joshua-Riek** [comment]
Hmm strange. I made some recent updates so please try and pull the latest code, then run build.sh.

It looks like the script build-rootfs.sh did not create the tar files for some reason. 
I will create a Ubuntu 18.04.6 TLS VM and test the build process and report my findings. I'm currently using Ubuntu 20.04 TLS as a build environment.

**Comment by Joshua-Riek** [comment]
I was able to build without any error on a fresh Ubuntu 18.04.6 TLS VM. Please make sure to download the required packages under the requirements in the [readme](https://github.com/Joshua-Riek/ubuntu-apalis-imx8#requirements), pull the latest source, and run build.sh. I have a log of the entire build process [here](https://github.com/Joshua-Riek/ubuntu-apalis-imx8/files/9450112/build.log) if it will help.

I also added a commit to better handle this type of error https://github.com/Joshua-Riek/ubuntu-apalis-imx8/commit/b8eaf70c56bc3e773a135a9e9ff71087aeab712e.

uname -a
Linux ubuntu 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Joshua-Riek** [comment]
If you encounter this issue again please let me know.
