### ISSUE TITLE
22.04?

### ISSUE THREAD

**Issue by JasonRScherer** [Joshua-Riek/ubuntu-apalis-imx8#5]
Have you had any luck getting 22.04 running with most of these scripts?  I got the packages to be correct but I just get a black screen in the end and wanted to see if I could try getting 22.04 for longer support.

**Comment by Joshua-Riek** [comment]
I've not really been paying attention to the iMX8 SOC anymore. It has poor performance and software support.

**Comment by JasonRScherer** [comment]
Makes sense, thank you and totally understandable.  Making images for it is rough.
